# Generated by Django 6.0.5 on 2026-06-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aportalapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userutilities',
            name='user_image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
