# Generated by Django 6.0.4 on 2026-05-07 22:09

import aportalapi.models.charts
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aportalapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='chart_image',
        ),
        migrations.AddField(
            model_name='chart',
            name='chart_file',
            field=models.FileField(blank=True, upload_to='', validators=[aportalapi.models.charts.validate_chart_file]),
        ),
    ]
