# Generated by Django 6.0.4 on 2026-05-08 15:00

import aportalapi.models.lyrics
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aportalapi', '0002_remove_chart_chart_image_chart_chart_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lyrics_file', models.FileField(upload_to='', validators=[aportalapi.models.lyrics.validate_lyrics_file])),
                ('chart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics', to='aportalapi.chart')),
            ],
        ),
    ]
