# Generated by Django 6.0.4 on 2026-05-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aportalapi', '0002_alter_userutilities_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userutilities',
            name='apple_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userutilities',
            name='spotify_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userutilities',
            name='user_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userutilities',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
    ]
