# Generated by Django 6.0.4 on 2026-05-08 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aportalapi', '0003_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupsheet',
            name='chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_chart', to='aportalapi.chart'),
        ),
    ]
