# Generated by Django 6.0.4 on 2026-05-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aportalapi', '0003_alter_userutilities_apple_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupsheet',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
